### ISSUE TITLE
XXE Vulnerability

### ISSUE THREAD

**Issue by dahua966** [processwire/processwire#181]
When getting an image file's information, the program does not care about XXE vulnerability, which could lead to sensitive information leakage or DoS attack.
In Pageimage class(wire\core\Pageimage.php), function `getImageInfoSVG` parses file without any sanitation ,whose content may contain attack vectors.
```php
	protected function getImageInfoSVG($filename = '') {
		$width = 0;
		$height = 0;
		if(!$filename) $filename = $this->filename;
		$xml = @file_get_contents($filename);
		
		if($xml) {
			$a = @simplexml_load_string($xml)->attributes();
```

**Comment by ryancramerdesign** [comment]
Thanks @dahua966, ProcessWire doesn't have SVG image uploads enabled by default, in part because of the uncertainties like this. An administrator can add SVG as an upload option for trusted admin users if they manually add the "svg" extension to the config settings themselves. I think it might make sense to add a warning if they add "svg" as an option. Though am interested to hear what @adrianbj thinks and whether his SVG sanitizer might also be another route. We could always require the administrator install it if they want to offer an SVG upload option. I'll close this issue because this repo isn't used or monitored for issues (we have a different repo for that), but we can keep the conversation going. Thanks.

**Comment by adrianbj** [comment]
@ryancramerdesign - I think the SVG sanitizer is probably the correct route. However, I should probably update the logic because it currently uses a modified version of https://github.com/alnorris/SVG-Sanitizer. I think it would probably be best if I migrated to using something that is more actively maintained, eg: https://github.com/darylldoyle/svg-sanitizer

Are you thinking about including this in the PW core, or just strongly recommending it if someone enables the SVG extension for a files field?

**Comment by ryancramerdesign** [comment]
@adrianbj I'm thinking it should recommend they install your module if they add SVG to the allowed upload extensions for a particular files/images field. That way at least people will understand that it involves more consideration than the other image formats, and they can decide whether that'll be something they need to consider or not. For instance, if they've got an installation where non-superusers are uploading SVG files then it would be a good idea for them to install your module. We could require it, but a lot of PW installs are superuser-only on the admin side so I think best just to give the admin a heads up that they should consider it and install your module if it applies to their setup. I don't hear about people using SVG for image uploads in PW very often, as I think it's something more likely during the development side. But would be good to cover it just in case.

**Comment by teppokoivula** [comment]
> I don't hear about people using SVG for image uploads in PW very often, as I think it's something more likely during the development side.

Just for the record, I use SVG image uploads a lot. Logos, icons, etc. are pretty much always saved as SVG's, and these are often files that the client manages via admin :)

**Comment by ryancramerdesign** [comment]
@teppokoivula You've got some smart clients. I don't think any of my clients even know what SVG is. For me SVG use is limited to web development, but I might just be old school. If your clients are uploading SVGs then I think that's a case where it would be good to have something more because while the users may be trusted, the source of the SVG files might not be. And even if folks know what SVG files are and use them, they might not understand they have different factors to consider than with other types of images. I think Adrian's FileValidatorSvgSanitizer module is what you need. I've also written a FileValidatorImage module, but it is purely for non-vector (bitmap) images: jpg, gif, png. 

@adrianbj Do you mind if I add an update that asks folks to install your FileValidatorSvgSanitizer module when they are using SVG files? Or did you want to do more with it? (you mentioned wanting to update logic). One thing that I think would be worthwhile is putting it in the ProcessWire namespace so that PW doesn't have to compile it.

**Comment by brettwilcox** [comment]
@ryancramerdesign @adrianbj  We use SVG's quite a bit as well. We're definitely interested in sanitation eventually making its way to core, but support the notification.

**Comment by ryancramerdesign** [comment]
@adrianbj I forgot that you and I had co-developed that SVG sanitizer library back in 2015. I will update the module here to use @darylldoyle svg-sanitizer library.

@brettwilcox Inclusion in the core is not an option as the svg-sanitizer library is GPL while ProcessWire is MPL 2.0 and some MIT. Though I'm no expert on SVG or any other file format, so can't keep up with all the potential issues of various file formats that someone may choose to allow in PW. The FileValidatorModule interface was built for this purpose, but SVG seems like a good one to warn about regardless.

**Comment by adrianbj** [comment]
@ryancramerdesign - go for it - happy for you to do whatever you think is best in terms of updating to that other library and also warning devs that it should be installed.

Regarding SVGs in general - I don't think it's a matter of having smart clients, I think it's a matter of educating clients - SVGs just make so much sense for almost all non-photo images, because as we all know, resizing (up and down) of these types of images (when they are raster) almost always results in poor quality. Once you demonstrate that to a client, it's much easier to get them on board.

**Comment by LostKobrakai** [comment]
Also with adobe loosing market share to alternative tooling (sketch/figma/affinity/…) and companies increasingly needing to deal with digital on many fronts svg seems to become more and more the vector format of choice for its great compatibility.

**Comment by brettwilcox** [comment]
We are starting to use [Draw.io](https://github.com/jgraph/drawio-desktop/releases) for some of our architectures and co-locating in produced .svg in the repo. It's nice to see a drawing directly on GitHub.

**Comment by ryancramerdesign** [comment]
@adrianbj I've rebuilt the module with the @darylldoyle library and it is located here: https://github.com/ryancramerdesign/FileValidatorSvgSanitizer — if you get a chance to try it out, please let me know if you run into any issues with it. Thanks.

**Comment by adrianbj** [comment]
@ryancramerdesign - looks good!

One thing I noticed though - when you upload a dirty SVG that it can't successfully sanitize, it reports "File Validation Failed" - so far, so good, but if you proceed to upload a different file, that error message is not removed, so you don't know whether the new file has worked or not, which is obviously confusing.

**Comment by ryancramerdesign** [comment]
@adrianbj Thanks for testing. I'm updating that error message to include the file basename so it's clear which file it's referring to.

Alright if I update the modules directory to point to the repo with the new version, or do you prefer to copy it into your existing repo?

**Comment by adrianbj** [comment]
> I'm updating that error message to include the file basename so it's clear which file it's referring to.

I don't think that necessarily helps. Someone might upload a different version of the image with the same filename. 

> Alright if I update the modules directory to point to the repo with the new version, or do you prefer to copy it into your existing repo?

Seems like this is your baby now, so probably best for you to maintain it, so long as you're going to keep up with updating the core library which is obviously important for something that is dealing with potential vulnerabilities.

**Comment by adrianbj** [comment]
Actually, one more thing I am a bit confused about is why it is arbitrarily removing url links. See their example here: http://svg.enshrined.co.uk/

There are plenty of times when it's perfectly OK to include these. I think the module needs options to let us set the library's `setAllowedTags` and `setAllowedAttrs` options so we can allow these if needed.

**Comment by adrianbj** [comment]
Sorry, maybe this is due to the remote references option :)

**Comment by adrianbj** [comment]
I still think the `setAllowedTags` and `setAllowedAttrs` options are important, because sometimes I include custom attributes in my SVG files for dynamic coloring etc.

**Comment by ryancramerdesign** [comment]
@adrianbj This library is better than the old one in most respects, but as far as setting attributes and tags, it's not straightforward. You have to define a custom class that implements a specific interface in order to do it, and even then, they are a generic list of tags and a separate generic list of attributes, so there's no relations drawn between the two like in the previous version. So you've got this setup where any tag you've whitelisted allows any attribute you've whitelisted, rather than limiting attributes by tag. I think I can still add support though, but probably not till next week.
