### ISSUE TITLE
Allow more options to override for Image field in contexts

### ISSUE THREAD

**Issue by ivangretsky** [processwire/processwire#7]
Good day!

This is a feature suggestion.

I always look for a way to minimize the amount of fields in my PW installation, reuse them as much as I can. Template context help me a lot, but not with images. 

[This update](https://processwire.com/blog/posts/processwire-2.5.7-core-updates/#field-template-context-now-available-for-any-field-property) made it possible to override more options in custom fields. Why not allow more options to override for core fields?

It would make image fields much more reusable, if we could override these options:

- Maximum Files Allowed,
- Formatted value,
- Min and Max Image demensions

The more the better) Is there anything preventing this?

**Comment by ryancramerdesign** [comment]
Hi Ivan, max files allowed and min/max dimensions may be possible for us to support overrides on. Formatted value less likely, because that would change the value type of the field depending on template context.

Would it be possible for you to move this feature request to our new requests repo here (by opening an issue report): https://github.com/processwire/processwire-requests/issues

I'm closing this issues section completely and managing it from separate repos so that we can manage GitHub team access control and collaboration independently of commit access. 

Thanks,
Ryan
